### ISSUE TITLE
Your planner was a life saver

### ISSUE THREAD

**Issue by handyjellyfish** [carlosesilva/reinvent-planner#4]
Thank you so much for this - it really helped me get my eggs in a row organising my sessions!

I hope you don't mind - but your planner inspired me and so I copied and modified your json script for the interest page to generate a markdown file of your session list (in time order)

Can see it here - https://github.com/handyjellyfish/Re-Invent

Thanks!
Rich.

**Comment by carlosesilva** [comment]
Oh cool! and no, I don't mind it at all.
I am glad it was helpful for other people as well!

See ya at re:Invent 😄
