### ISSUE TITLE
Start and end times are null

### ISSUE THREAD

**Issue by abjoerne** [carlosesilva/reinvent-planner#7]
Session and location is available in the catalogue now. Unfortunately all sessions are being populated with null as start and end.

[{"id":"95852","link":"https://www.portal.reinvent.awsevents.com/connect/sessionDetail.ww?SESSION_ID=95852&csrftkn=5PVD-F8FM-27E4-XI4R-N3FM-65DD-IMOF-2UKO","abbreviation":"DAT403-R1","title":"[REPEAT 1] Amazon DynamoDB deep dive: Advanced design patterns","type":"Session","start":null,"end":null,"location":" – Venetian | Palazzo, Level 4, Delfino 4005 - T1"}

![image](https://user-images.githubusercontent.com/17033617/66255671-bcc26080-e786-11e9-918b-e8c4129a59ec.png)

Latest Firefox and Chrome on Mac

**Comment by ljacobsson** [comment]
I changed `getSessionDatetime` to this locally:

```
function getSessionDatetime(session) {
  const datetime = {
    start: null,
    end: null
  };
  try {
    const rawDatetime = session.querySelector(
      ".actionColumn .sessionTimes .availableSessions"
    ).childNodes[0].textContent;
    const date = rawDatetime.split(", ")[1] + " 2019";
    const [timeStart, timeEnd] = rawDatetime.split(", ")[2].split(" - ").map(p => p.split(/\u2013/)[0].trim());
    const datetimeStart = Date.parse(date + "," + timeStart);
    const datetimeEnd = Date.parse(date + "," + timeEnd);
    datetime.start = datetimeStart;
    datetime.end = datetimeEnd;
  } catch (error) {}

  return datetime;
}
```

Note the change in the selector and the split on the long dash between end time and venue (\u2013).
